repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: debug-statements
        files: \.py$
    -   id: trailing-whitespace
        files: \.(py|sh|yaml|txt)$
    -   id: name-tests-test
        files: tests/.+\.py$
    -   id: end-of-file-fixer
        files: \.(py|sh|yaml)$
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: requirements-txt-fixer
-   repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
-   repo: https://github.com/asottile/reorder_python_imports.git
    rev: v3.8.2
    hooks:
    -   id: reorder-python-imports
        language_version: python3.7
        args: [--py3-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
    -   id: pyupgrade
        args: ['--py37-plus']
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        language_version: python3.7
        exclude: setup.py
        args: [--target-version, py37]
