name: Build and Test

on:
 push:
   branches: [master]
   tags:
 pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          python-version: ['3.7']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: python -m pip install tox

    - name: Run ${{ matrix.python-version }} tox
      run: tox -e py
